name: Publish to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build ./.#catt-web
      - id: find-web-path
        run: |
          path=$(nix eval ./.#catt-web.outPath --raw)
          echo "web-path=$path" >> "$GITHUB_OUTPUT"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ steps.find-web-path.outputs.web-path }}/share